name: setup gitconfig
description: set up gitconfig with an org PAT to clone private repos
inputs:
  ORG_GITHUB_TOKEN:
    description: 'organizational personal access token with read private repositories permission'
    required: true

runs:
  using: composite
  steps:
    - name: Set up gitconfig to clone github private repositories
      run: git config --global url."https://${{ inputs.ORG_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      shell: bash
