name: continuous-integration

on:
  pull_request:
    branches:
      - feat/**
      - fix/**
      - hotfix/**
  push:
    branches:
      - main

env:
  NODE_VERSION: 14
  GO_VERSION: 1.22.0

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: $NODE_VERSION
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint '**/*.md'

  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: $GO_VERSION
      - name: Run go mod tidy
        run: go mod tidy

#  go-lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: $GO_VERSION
#      - name: Install golangci-lint
#        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
#      - name: Run golangci-lint
#        run: golangci-lint run

#  go-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: '1.16'
#      - name: Run tests
#        run: go test ./... -v