name: terraform-continuous-integration

on:
  pull_request:
    branches:
      - feat/**
      - fix/**
      - hotfix/**
      - main
  push:
    branches:
      - main

env:
  GOPRIVATE: github.com/intercloud
  TF_VERSION: 1.9.0
  TF_MODULE_PATH: examples/autonomi

jobs:
  tf-validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: terraform init
        working-directory: ${{ env.TF_MODULE_PATH }}
        run: terraform init
      - name: terraform validate
        working-directory: ${{ env.TF_MODULE_PATH }}
        run: terraform validate

  tf-plan:
    runs-on: ubuntu-latest
    needs:
      - tf-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: terraform plan
        working-directory: ${{ env.TF_MODULE_PATH }}
        run: terraform plan
